services:
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.9}
    container_name: ${CONTAINER_NAME:-email-service}
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-5000}:${SERVICE_PORT:-5000}"
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - SERVICE_PORT=${SERVICE_PORT:-5000}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TIMEZONE:-UTC}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-120}
      - API_KEY=${API_KEY:-} # Chave de API para autenticação
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8000,https://fsw-ifc.brdrive.net}
    volumes:
      - ${LOG_DIR:-./logs}:/app/logs
    networks:
      - fabrica-service-network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:${SERVICE_PORT:-5000}/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-10s}
    # Limitar recursos
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    # Desabilitar acesso ao sistema de arquivos root
    read_only: true
    # Diretórios temporários necessários
    tmpfs:
      - /tmp
      - /var/run

networks:
  fabrica-service-network:
    driver: bridge
    # Configurações adicionais de segurança de rede
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
